name = "depression simulator"
default_targets = ["win32", "win64", "appimage", "lovejs", "macos"]
build_directory = "release"
icon_file = "icon.png"
keep_game_directory = true

love_files = [
    "::git-ls-tree::",
    "-*/.*",
]
